services:
  mailer:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  mercure:
    image: dunglas/mercure
    ports:
      - "3000:3000"
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '50ebfcf315794dbe3a19ca0d2105608f164366e083a4bb1426cd72ec41c42fbd'
      MERCURE_SUBSCRIBER_JWT_KEY: '50ebfcf315794dbe3a19ca0d2105608f164366e083a4bb1426cd72ec41c42fbd'
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins *
